### ISSUE TITLE
BE: add platformFee Calculation in Payment Service

### ISSUE THREAD

**Issue by ArJSarmiento** [SPARCS-UP-Mindanao/SPARCS-Payment-Service#10]
In the Payment Service, modify `/fees` API in `controller/transaction_router.py`

It should take an optional `platformFee` field to be passed from the frontend.

In `get_transaction_details`, add the platform fee to the ticket_price variable if it exists 

![Image](https://github.com/user-attachments/assets/03ccc694-2e22-4b2a-ac2f-a971b34a1c9f)

Add the platformFee to the `GetTransactionDetailsOut` model

![Image](https://github.com/user-attachments/assets/9a908c83-c5d0-450c-b98f-1f3356ed8d5c)

Deploy changes to dev and test if everything else is still working.

Attach a recording to this ticket after code approval as proof.

**Inform Arnel if you are about to begin the task for AWS Credentials**

**Comment by ArJSarmiento** [comment]
PR merged @44mira . Please do an end-to-end test on dev environment. Attach a recording to this ticket showing that it's functional **with or without the platformFee**. Once done, please move ticket to Done. Thanks!

**Comment by 44mira** [comment]
https://github.com/user-attachments/assets/d1a14bb3-3724-46ad-bb5a-3e39addaf68e
